web1/blog/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from . import views


app_name = 'blog'
urlpatterns = [
   re_path(r'^$', views.index),
   re_path(r'^article/(?P<article_id>\d+)$', views.article_page, name='article_page'),
   re_path(r'^edit/(?P<article_id>\d+)$', views.edit_page, name='edit_page'),
   re_path(r'^edit_action/$', views.edit_action, name='edit_action'),
]

web1/cmdb/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from cmdb import views

urlpatterns = [
   re_path(r'^$', views.index),
]

web1/web1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cmdb/', include('cmdb.urls')),
    path('blog/', include('blog.urls', namespace='blog')),
]

web1/blog/models.py
from django.db import models

# Create your models here.


class Article(models.Model):
    title = models.CharField(max_length=32, default='Title')
    content = models.TextField(null=True)
    create_time = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

web1/cmdb/models.py
from django.db import models

# Create your models here.


class UserInfo(models.Model):
    user = models.CharField(max_length=32)
    pwd = models.CharField(max_length=32)

web1/blog/views.py
from django.shortcuts import render
from django.shortcuts import HttpResponse
from django.http import HttpResponseRedirect
from . import models


# Create your views here.


def index(request):
    articles = models.Article.objects.all()
    return render(request, 'blog/index.html', {'articles': articles})

def article_page(request, article_id):
    article = models.Article.objects.get(pk=article_id)
    return render(request, 'blog/article_page.html', {'article': article})

def edit_page(request, article_id):
    if str(article_id) == '0':
        return render(request, 'blog/edit_page.html')
    article = models.Article.objects.get(pk=article_id)
    return render(request, 'blog/edit_page.html', {'article': article})

def edit_action(request):
    title = request.POST.get('title', 'TITLE')
    content = request.POST.get('content', 'CONTENT')
    id = request.POST.get('article_id', '0')
    if id == '0':
        models.Article.objects.create(title=title, content=content)
    else:
        models.Article.objects.filter(pk=id).update(title=title, content=content)
    return HttpResponseRedirect('/blog/')

web1/cmdb/views.py
from django.shortcuts import render
from django.shortcuts import HttpResponse
from . import models

# Create your views here.


def index(request):
    if request.method == 'POST':
        username = request.POST.get('username', None)
        password = request.POST.get('password', None)
        # print(username, password)
        models.UserInfo.objects.create(user=username, pwd=password)
    user_list = models.UserInfo.objects.all()
    return render(request, 'index.html', {'data': user_list})

web1/blog/templates/blog/article_page.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">      
        <title></title>
    </head>
    <body>
        <h1 style="background-color:antiquewhite;color:black;">{{ article.title }}</h1>
        <br/>
        <h3>{{ article.content }}</h3>
        <br/><br/>
        <a href="{% url 'blog:edit_page' article.id %}">修改文章</a>
    </body>
</html>

web1/blog/templates/blog/edit_page.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">      
        <title>添加文章</title>
    </head>
    <body>
        <form action="{% url 'blog:edit_action' %}" method="POST">{% csrf_token %}
            <input type="hidden" name="article_id" value="{{ article.id | default:'0' }}"/>         
            {% if article %}
            <label>文章标题
                    <input type="text" name="title" value="{{ article.title }}"/>
            </label>
            <br/>
            <label>文章内容
                    <input type="text" name="content" value="{{ article.content }}"/>
            </label>
            <br/>
            {% else %}
            <label>文章标题
                    <input type="text" name="title"/>
            </label>
            <br/>
            <label>文章内容
                    <input type="text" name="content"/>
            </label>
            <br/>
            {% endif %}
            <input type="submit" value="提交">
        </form>
    </body>
</html>

web1/blog/templates/blog/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">      
        <title>首页</title>
    </head>
    <body>
        <h1 style="background-color:antiquewhite;color:black;">
            <a href="{% url 'blog:edit_page' 0 %}">新文章</a></h1>
        <h2>
            {% for article in articles %}
                <a href="{% url 'blog:article_page' article.id %}">{{ article.title }}</a>
                <br/>
            {% endfor %}
        </h2>
    </body>
</html>

web1/templates/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">      
        <title>首页</title>
    </head>
    <body>
        <h1 style="background-color:antiquewhite;color:black;">首页</h1>
        <h1 style="background-color:antiquewhite;color:black;">
            <form action="/cmdb/" method="POST">{% csrf_token %}
                用户名：<input type="text" name="username"><br>
                密码：<input type="text" name="password">
                <input type="submit" value="提交">
            </form>
            <h1 style="background-color:antiquewhite;color:black;">
                <table>
                    <thead>
                        <th>用户名</th>
                        <th>密码</th>
                    </thead>
                    <tbody>
                        {% for user in data %}
                            <tr>
                                <td>{{ user.user }}</td>
                                <td>{{ user.pwd }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
            </table>
            </h1>
        </h1>
    </body>
</html>